### ISSUE TITLE
how to run from exe

### ISSUE THREAD

**Issue by murunwas** [ruidfigueiredo/electron-cgi#1]
how to connect the app from published .exe? 
`.connectTo('dotnet', 'run', '--project', 'app.exe')` does not work

**Comment by ruidfigueiredo** [comment]
the syntax for connectTo is: `.connectTo(executableOrFullPathToExecutable, Parameter1, Parameter2, ...)` so if app.exe is your published executable you can do:
`connectTo('pathToApp/app.exe')`

**Comment by murunwas** [comment]
thank you so much... it works like charm
