### ISSUE TITLE
Response handler example in documentation always receives `null`

### ISSUE THREAD

**Issue by rcook** [ruidfigueiredo/electron-cgi#10]
Response handler in example in documentation appears to be wrong:

```
connection.send('greeting', 'John', theGreeting => {
    console.log(theGreeting); // will print "Hello John!"
});
```

`theGreeting` is always `null`. This is confirmed by looking at the code which invokes the response handler:

https://github.com/ruidfigueiredo/electron-cgi/blob/master/connection.js#L25

This change was introduced in https://github.com/ruidfigueiredo/electron-cgi/commit/2d075547087ce923eb2107495847cfe974afcbed.

So, I assume that this handler signature change is intentional and that the documentation is just out of date.

**Comment by ruidfigueiredo** [comment]
Hi @rcook 

Thanks for letting me now and the pull request! (it's incorporated version 1.0.5)

That error will be the serialized .NET exception if one is thrown in the request handler in .NET.

You can also use async/await (or just use promises) now:

    try{
        const greeting = await connection.send('greeting', 'John');
        console.log(greeting);
    }catch (err) {
        console.log(err); //err is the serialized exception thrown in the .NET handler for the greeting request
    }

or

    connection.send('greeting', 'Richard').then(theGreeting => {...}, error => {...})
