### ISSUE TITLE
Package uploaded to NPM should not include .git directory

### ISSUE THREAD

**Issue by rcook** [ruidfigueiredo/electron-cgi#12]
This causes future `npm install` commands to fail as follows:

```
npm ERR! code EISGIT
npm ERR! path /Users/name/src/electron-typescript-app/node_modules/electron-cgi
npm ERR! git /Users/name/src/electron-typescript-app/node_modules/electron-cgi: Appears to be a git repo or submodule.
npm ERR! git     /Users/name/src/electron-typescript-app/node_modules/electron-cgi
npm ERR! git Refusing to remove it. Update manually,
npm ERR! git or move it out of the way first.
```

This also interferes with the use of `git clean` and other git commands in the referencing project.

**Comment by ruidfigueiredo** [comment]
Hey @rcook 

Thanks for letting me know. Seems like I my last publish was affected by this [npm](https://github.com/npm/npm/issues/20213) issue.

I've just published version 1.0.5.

Guess from now on I'll do a `--dry-run` first.
