### ISSUE TITLE
Unable to get type of Connection in typescript

### ISSUE THREAD

**Issue by Cidolfas** [ruidfigueiredo/electron-cgi#13]
I was trying to use electron-cgi in a typescript electron application and had an issue because I couldn't get the Connection type since the change in #9 removed exporting it from index.d.ts

The specific code in my app that wants me to have Connection's type is:

```
let connection: Connection; // <- where I need the Connection type
if (process.env.NODE_ENV === 'production') {
  connection = new ConnectionBuilder()
    .connectTo('dotnet', './resources/server/server.dll')
    .build();
} else {
  connection = new ConnectionBuilder()
    .connectTo('dotnet', 'run', '--project', '../server')
    .build();
}
```

Adding `export {Connection} from './connection'` to index.d.ts lets me use `import { ConnectionBuilder, Connection } from 'electron-cgi';` in my app, which solves the issue for me.

Is there an alternate way to get the type of Connection, or should it be added back to index.d.ts?

**Comment by ruidfigueiredo** [comment]
Hi @Cidolfas,

Thanks for the heads up.

Added it to index.d.ts. Published in version 1.0.5 of the npm package, it should be available shortly
