### ISSUE TITLE
Electron-Cgi Packaged version is not working but Dev is Working

### ISSUE THREAD

**Issue by bhumaanu** [ruidfigueiredo/electron-cgi#14]
Hi, I have similar problem as Tim Antonius mentioned [here: https://github.com/ruidfigueiredo/electron-cgi/issues/2](https://github.com/ruidfigueiredo/electron-cgi/issues/2) My app works in development mode. But when I packaged it, it stopped working. I understand that the dotnet csproj path might change in packaged version and I checked in resource folder as you mentioned. But in resource folder, I see only icons. Also, I couldn't find where logs are stored. Can you please help me with package version and logs?

<img width="594" alt="error" src="https://user-images.githubusercontent.com/57880513/83519983-8ba75500-a4fa-11ea-9700-92091d8e07db.PNG">

**Comment by bhumaanu** [comment]
[https://github.com/ruidfigueiredo/electron-cgi/issues/2](https://github.com/ruidfigueiredo/electron-cgi/issues/2)

**Comment by ruidfigueiredo** [comment]
Hi @bhumaanu 

Can you provide a little bit more info, namely:

How did you package your app? 

Did you use dotnet publish to create an executable for the .NET part?

What was the location of the .NET executable when you created the package?

**Comment by bhumaanu** [comment]
Hi @ruidfigueiredo 

I used dotnet run. I packaged my app with electron-builder. I resolved the issue by changing the path to csproj file in packaged version. That clears my problem. I have few other issues or questions as below

1. Can I use dotnet publish instead of dotnet run so that app always talks to dll/exe?
2. Right now, my app is establishing connection to dotnet each and every time to dotnet. Is there a way that electron-cgi supports onetime connection until I quit the application?


I would like to thank you for making life easier with electron-cgi which enabled connection between node and .net.

**Comment by ruidfigueiredo** [comment]
> Can I use dotnet publish instead of dotnet run so that app always talks to dll/exe?

Yes, you should definitely do this. You can use --self-contained to generate an executable that does not require the end user to have the dotnet sdk installed

> Right now, my app is establishing connection to dotnet each and every time to dotnet. Is there a way that electron-cgi supports onetime connection until I quit the application?

Don't really understand what you mean but let me know if the following helps:

Usually there's only one .net process running, i.e. each time you create a "connection" one process is started and will only be terminated when you "close" the connection.
You can however create as many connections as you like, and each will launch a new .net process.

The usual case is that you create one connection and use it until you quit your app, so there should only be 1 .net process running in tandem with the electron app

**Comment by bhumaanu** [comment]
Hi @ruidfigueiredo , 
I have Folder Structure of Application as
![image](https://user-images.githubusercontent.com/57880513/83906125-9f63ed00-a780-11ea-9cd0-c97ae570a692.png)


1) My index.js is located in Demo >> ClientApp
I ran dotnet publish on my Demo.csproj folder (which is "Demo") from command prompt. It generated exe file in Demo >> bin >> Debug >> netcoreapp3.1
While establishing connection, I am not sure how to connect to exe that is sitting in above specified folder. I have trouble replacing dotnet 'run' in connectTo line to use exe. Do you have any code snippet that runs using exe instead of dotnet run command?

previous working connection with source code:
![image](https://user-images.githubusercontent.com/57880513/83897079-b69bde00-a772-11ea-9846-a16116f345f5.png)


2. My app is using C#, Electron-cgi, React.  I have single page which has 4 buttons. When user clicks on any of these 4 buttons, app needs to talk to dotnet and perform its action. Currently app works fine by establishing separate connections in each button click. This eats up lots of time having user to wait everytime he clicks on a button since it needs to establish connection, and build it. So, I thought of creating 1 single connection for entire page, which is not working. In the below image, you can see that I am establishing connection in React.useEffect., When I am in onGetListClick there is error thrown saying connection.send is not a function. 
Note: Connection is working for me only when I create it locally in that button click handler. 
Let me know if I did go wrong anywhere.

![image](https://user-images.githubusercontent.com/57880513/83904223-1b5c3600-a77d-11ea-9bce-9ca9d8d15426.png)

**Comment by ruidfigueiredo** [comment]
> Do you have any code snippet that runs using exe instead of dotnet run command?

`const connection = new ConnectionBuilder().connectTo('pathToTheExecutable/theExecutable')`

You don't need to use `dotnet run`, just connect to the executable. Note that before you package your app you have to put the executable somewhere where the particular packager you are using (e.g. electron-builder) picks it up and includes it in the package. You also have to make the `pathToTheExecutable` points to the executable "inside" the package.

> In the below image, you can see that I am establishing connection in React.useEffect., When I am in onGetListClick there is error thrown saying connection.send is not a function.

`let connection = new ConnectionBuilder()`
`connection` here is a reference to the connection builder and not the connection.

`connection.connectTo(...).build()` returns the connection but you are not storing it anywhere.

Also, the function in useEffect will be called each time the component is rerendered, you definitely don't want to do that.

Have a look at the demo project: https://github.com/ruidfigueiredo/MemorizeADeck which is also a react app. Namely how the connection is created and shared between electron and the react app in electron's preload.js.

**Comment by bhumaanu** [comment]
Hi, I tried creating connection in preload.js and shared across react. It worked in dev version but not in packaged version. Please refer to screenshot and let me know if I need to do anything different. Also, please let me know if I need to include preload.js in webpack?

![image](https://user-images.githubusercontent.com/57880513/84827941-e08eb380-b042-11ea-8364-9662d195c58d.png)

![image](https://user-images.githubusercontent.com/57880513/84828172-3d8a6980-b043-11ea-81e4-82df61572bda.png)

**Comment by ruidfigueiredo** [comment]
Hi @bhumaanu 

Hard to understand what is wrong with just that information.

When you ask if you need to include preload.js in webpack what do you mean? Are you trying to somehow load preload.js from the React app?

**Comment by bhumaanu** [comment]
Rui,

 App works fine in dev mode. When I package app with electron builder, it threw me below error
![image](https://user-images.githubusercontent.com/57880513/84831299-b6d88b00-b048-11ea-8d47-23d29a5c0f66.png)
I see it is looking for preload.js from app.asar. If it is fine with you sharing an email id, i can send you my whole application which I cannot upload here. Thanks

**Comment by ruidfigueiredo** [comment]
I can have a look:
rui @ blinkingcaret.com

**Comment by bhumaanu** [comment]
Hi Rui,

Sorry, I cannot send you the solution as I am unable to export it. Here is more information. Let me know if you need anymore info

WebPreferences:
![image](https://user-images.githubusercontent.com/57880513/84915135-10d56100-b0da-11ea-8b1c-6625e2dd9dff.png)

Preload.js:
![image](https://user-images.githubusercontent.com/57880513/84915170-19c63280-b0da-11ea-8a48-51b1da204ecb.png)

Connection.js
![image](https://user-images.githubusercontent.com/57880513/84915203-221e6d80-b0da-11ea-952a-332cc9e74d52.png)

App is working as expected in dev. But is throwing below error in packaged version. It is unable to find preload.js in packaged version.
![image](https://user-images.githubusercontent.com/57880513/84915312-3ebaa580-b0da-11ea-85f7-cf2a141ab043.png)

**Comment by ruidfigueiredo** [comment]
Check this: https://stackoverflow.com/questions/60814430/electron-builder-with-browserwindow-and-preload-js-unable-to-load-preload-scrip

The issue you are having seems to be missing electron-builder configuration
