### ISSUE TITLE
Can electron cgi work with an already built and obfuscated C# executable?

### ISSUE THREAD

**Issue by mxswat** [ruidfigueiredo/electron-cgi#15]
Hello, I'm working with a friend on making a modding tool for games.

My friend makes the entire pointer system and game modding code in C# and I need to take care of the UI;

I want to make clear that both the c# .exe and electron will run on the same machine and I cannot just add the C# project source to the electron project because It needs to be closed source and obfuscated to avoid misuse of our code.
So, can electron-cgi work with an already built and obfuscated C# executable?

**Comment by ruidfigueiredo** [comment]
Hi @mxswat 

If you can make a C# console application that uses the C# code you already have, then yes, and that can be obfuscated too, really doesn't matter.

**Comment by mxswat** [comment]
Hi @ruidfigueiredo Thanks for the quick answer I have another question 
this means that I can just do 
`const connection = new ConnectionBuilder()
        .connectTo('dotnet', 'run','Editor.exe')
`
Without having to load the project?

**Comment by ruidfigueiredo** [comment]
@mxswat Actually, less than that:

`const connection = new ConnectionBuilder() .connectTo('Editor.exe')`

Don't really know what you mean by loading the project. The thing is, Editor must be be using with the ElectronCgi.DotNet nuget package and have the appropriate configuration for receiving the type of requests you need from node

**Comment by mxswat** [comment]
Oh, this is amazing, also is there any docs for the entire electron-cgi project?

**Comment by ruidfigueiredo** [comment]
Hi @mxswat thanks!

There are a few blog posts:

https://www.blinkingcaret.com/2020/03/25/electroncgi-1-0-cross-platform-guis-for-net-core/

https://www.blinkingcaret.com/2019/11/27/electroncgi-a-solution-to-cross-platform-guis-for-net-core/

And there are a few examples apps, the latest one I built was this: https://github.com/ruidfigueiredo/MemorizeADeck

There's also a podcast episode about ElectronCgi if you are interested in the story behind it: https://www.automator.show/18

**Comment by mxswat** [comment]
@ruidfigueiredo thank you so much for the time you are using to help me

**Comment by mxswat** [comment]
I was able to make electron cgi launch the .exe 

When I added  `connection.Send("greetingx", "hello from c#");` on the C# file 
and on the the .ts file i added the on
`connection.on('greetingx', (request) => {
  console.log(request);
});`
But I got this error

![image](https://user-images.githubusercontent.com/17874432/85342350-b2015480-b4ea-11ea-87ef-54555db7d48b.png)

What can be the cause of the problem?

**Comment by ruidfigueiredo** [comment]
"Hello World from MessageService!" that was written to the stdout stream (there's a Console.WriteLine with that somewhere in C#).

ElectronCGI uses the stdout and stdin streams to build a communication channel between the two processes, if you write to those yourself you'll get those errors.

**Comment by mxswat** [comment]
So, I went in Debug inside the file `tab-separated-input-stream-parser.js` and I noticed it just now!

My brain completely ignored "Hello World from MessageService!"
This is what happens when I keep coding at 2AM lol

I guess I should attach a custom console to have console logs in the C# project, not a big deal

**Comment by mxswat** [comment]
My brain completely ignored "Hello World from MessageService!" 
This is what happens when I keep coding at 2AM lol

**Comment by mxswat** [comment]
So I guess I should attach a custom console to have console logs in the C# project, not a big deal

**Comment by mxswat** [comment]
It works perfectly now
