### ISSUE TITLE
Use electron-cgi with windows application made with windows form

### ISSUE THREAD

**Issue by mxswat** [ruidfigueiredo/electron-cgi#16]
I'm trying to convert a "windows form" application   to work with electron-cgi because I want the entire UI to be made with electron

I noticed that the windows form UI does not appear until I close the connection from electron is it possible to fix this?

I guess It might be because the current project is not multithread? 
Because when I remove the ConnectionBuilder code the form app appears

**Comment by ruidfigueiredo** [comment]
I imagine what you are trying to do is to be able to have both while you are developing? That's fine, if you want to do that just wrap connection.Listen(), which is blocking by design, in it's own task/thread:

`Task.Run(() => connection.Listen());`

And you should be fine.

**Comment by mxswat** [comment]
Thanks, I'll try it as soon as possible

**Comment by mxswat** [comment]
Works perfectly!

@ruidfigueiredo  You are the best and this lib is incredible
