### ISSUE TITLE
Missing executable file in snap package

### ISSUE THREAD

**Issue by fairking** [ruidfigueiredo/electron-cgi#20]
My repo is here: https://github.com/fairking/electron-cgi-calculator-demo

If I try to run the project everything works fine so far.

But if I create a snap package and then install it on the linux machine the line:
```
_connection = new ConnectionBuilder().connectTo('./DotNetCalculator/DotNetCalculator').build();
```
the line complains about missing `DotNetCalculator` file.

Can somebody help to figure out what is going on?

The file is definitely there.

Thanks

**Comment by fairking** [comment]
Ok, I found an issue. It was because of missing `enableRemoteModule: true,` I quess.

But the connection with the EXE is not working.

**Comment by ruidfigueiredo** [comment]
Hi @fairking 

I suggest you try going to your /snap/folderWithYourAppsSnapName and looking for the location where the executable ended up inside the snap.

**Comment by fairking** [comment]
I'm giving up. Making a normal RPM. I have a bad experience with all that SNAP stuff.

**Comment by ruidfigueiredo** [comment]
Good luck

**Comment by fairking** [comment]
> I suggest you try going to your /snap/folderWithYourAppsSnapName

I tried many different ways. It says "File not found" or "Exited with code 1" or something else but it never worked.

You can see yourself if you are interested. It is very simple example. Nothing complicated. https://github.com/fairking/electron-cgi-calculator-demo

By the way thanks for the reply.

**Comment by fairking** [comment]
I managed to create a rpm package with no issues. Installed version is working fine. Thanks @ruidfigueiredo .

**Comment by ruidfigueiredo** [comment]
@fairking Thanks for letting me know!
