### ISSUE TITLE
Building the app

### ISSUE THREAD

**Issue by domialex** [ruidfigueiredo/electron-cgi#21]
What would be the correct way to build and bundle with a built .NET application?

**Comment by domialex** [comment]
Ah never mind, I guess it could just run the executable in the build folder of the node project.

**Comment by ruidfigueiredo** [comment]
Hi @domialex 

That's right, you just have to make sure that you "point" to the right location of the executable when the app is packaged. 

One thing that is useful to know is that it is possible to use `dotnet publish` to create a "self contained" version of your .net app (i.e. whoever installs your app doesn't have to install `dotnet`). 

I've just noticed that there's an option to create a single file with the flag `-p:PublishSingleFile=true`, might be interesting to try. Although that single file will decompress on first run so I'm not sure if that won't cause any issues.

**Comment by domialex** [comment]
The single file publish is useful, but most times will trigger an invisible anti-virus warning in Windows 10, and it won't be able to extract the temporary files. The normal publish is more reliable.

**Comment by fairking** [comment]
Hi @domialex 
I recently was playing with `electron-builder` #20 . I wasn't able to create a snap but I created a setup file for windows and also a rpm package for linux.
You can find my demo project here: https://github.com/fairking/electron-cgi-calculator-demo
More info about electron-builder: https://www.electron.build/

**Comment by domialex** [comment]
Thanks! I already have all that part figured out (packaging, installer, webpack, react, etc.), I also used electron-builder.
