### ISSUE TITLE
State of electron-cgi/c# debug question

### ISSUE THREAD

**Issue by trusinaj** [ruidfigueiredo/electron-cgi#24]
Hey,

great package you have going on here, I really like it.

Im starting new project and Im looking for solution that connects c# with electron and I like your solution to this.

I just wanted to ask if this package is still being worked on what is current state.

And one more question, is there a posibility to connect to running c# project in debug mode and debug my c# code?

I havent found anything about this.

Thanks J.

**Comment by ruidfigueiredo** [comment]
Hey @trusinaj 

I have only updated the project when someone has a feature request or a bug. There haven't been many of those lately.

Yes, you can debug the C# code. When you start your electron app a new c# process is started up and you can attach the debugger to it, add breakpoints etc. There's a video here that shows how to do that: https://www.blinkingcaret.com/2019/11/27/electroncgi-a-solution-to-cross-platform-guis-for-net-core/#better-debugging
