### ISSUE TITLE
Electron CGI + angular + .net project

### ISSUE THREAD

**Issue by Agoldstein1** [ruidfigueiredo/electron-cgi#26]
Hi, 
I'm new in electron cgi ,
@ruidfigueiredo  - do you have an example of a project containing Angular + C# code + Electron cgi?
As I checked - all the examples you shared contain electron cgi + react.
it could help me a lot to do my first steps.
thanks

**Comment by ruidfigueiredo** [comment]
Unfortunately I don't have any samples with angular. It should be pretty similar though. Especially if you have nodeIntegration turned on (just be aware when running this way the code will have access to all your system (file system, etc) so, any code for that is loaded from a remote source is potentially a problem
