### ISSUE TITLE
Error Parsing JSON

### ISSUE THREAD

**Issue by myarasi8** [ruidfigueiredo/electron-cgi#30]
Hello,

I followed the instructions in the README as well as the tutorial you posted: https://www.youtube.com/watch?v=-aJDzyGgNLY

This is the code in index.js of the elctron-node-demo app:
```
const { ConnectionBuilder } = require('electron-cgi');

let connection = new ConnectionBuilder()
    .connectTo('dotnet', 'run', '--project', '../ElectronCgiDotNetDemo')
    .build();

connection.onDisconnect = () => {
    console.log('Connection between node and .net lost')
};

connection.send('greeting', 'Mahesh', response => {
    console.log("message is " + response);
    connection.close();
});
```

And this is the code in the .NET console app:
```
using System;
using ElectronCgi.DotNet;

namespace ElectronCgiDotNetDemo // Note: actual namespace depends on the project name.
{
    internal class Program
    {
        static void Main(string[] args)
        {
            var connection = new ConnectionBuilder()
                        .WithLogging()
                        .Build();

            // expects a request named "greeting" with a string argument and returns a string
            connection.On("greeting", (string name) =>
            {
                return $"Hello {name}!";
            });

            // wait for incoming requests
            connection.Listen();
        }
    }
}
```

When I run node index.js I get the following error:

![pic](https://github.com/ruidfigueiredo/electron-cgi/assets/15006207/37db12c5-9166-406c-82a8-80bea3a43ad8)

As you can see it is generating the JSON object from the console app correctly:
```{"type":"RESPONSE","response":{"result":"Hello Mahesh!","id":"4529207b-c562-4bd6-9155-45106dd06054"}} ```

But it is erroring at this line in the elctron-cgi code:
![pic2](https://github.com/ruidfigueiredo/electron-cgi/assets/15006207/104a259c-5254-45bc-8884-fe909afdbdc2)

Are you able to reproduce this? Please let me know.

Thank you.

**Comment by mwahnish** [comment]
Just to second this, I'm getting the exact same issue running the instructions from the readme

**Comment by mwahnish** [comment]
Just to follow up - I solved my issue. I had a Console.WriteLine() running in my c# code prior to starting up the connection. Because this was writing to stdout, ElectronCGI was picking up the text from the Console.Writeline() as part of the JSON string. 

It looks like something similar is happening to the original reporter. Looking at the error message they are receiving, it looks like messages from their build process are getting written to stdout prior to the connection opening, which are getting prepended to the json

**Comment by myarasi8** [comment]
I put a console log statement in tab-seperated-input-stream-parser.js provided by electron-cgi:
![pic2](https://github.com/ruidfigueiredo/electron-cgi/assets/15006207/6ffc8884-0bc5-4dd8-ae60-139a2f2054d1)

This is the error:
![pic](https://github.com/ruidfigueiredo/electron-cgi/assets/15006207/3810455f-079c-4d8a-9235-44ee1684e385)

It looks like messageStr is the warning message and the json object concatenated together like so:
```
'C:\Users\{user.name}\Code\electrong-cgi\ElectronCgiDotNetDemo\ElectronCgiDotNetDemo.csproj : warning NU1803: You are running the 'restore' operation with an 'HTTP' source, 'http://svrdevfile01/nuget/nuget'. Non-HTTPS access will be removed in a future version. Consider migrating to an 'HTTPS' source.      
C:\Users\{user.name}\Code\electrong-cgi\ElectronCgiDotNetDemo\ElectronCgiDotNetDemo.csproj : warning NU1803: You are running the 'restore' operation with an 'HTTP' source, 'http://{user.name}/nuget/nuget'. Non-HTTPS access will be removed in a future version. Consider migrating to an 'HTTPS' source.
{"type":"RESPONSE","response":{"result":"Hello John!","id":"71d128e1-768e-4c8e-b3f4-9ac4970fe601"}}'
```

 This is why it's unable to perform JSON.parse(messageStr). I believe it should remove the warning message prior to performing the parse method. For now I am supressing the warning.

**Comment by ruidfigueiredo** [comment]
Hi @myarasi8 and @mwahnish 

The error indicates that there's more being written to the stdout stream than just the json. Everything after "Error: Invalid incoming JSON:" was on the stdout stream.

The error/warning message comes from the C# process (https://learn.microsoft.com/en-us/nuget/reference/errors-and-warnings/nu1803) 

> I believe it should remove the warning message prior to performing the parse method. For now I am supressing the warning.

If you are suggesting that it should be the electron-cgi library to remove it, I don't think that is reasonable. It would be more reasonable for the dotnet sdk to output that to the stderr stream. You can try opening a ticket there.

In the end you should fix the issue on the dotnet executable side, even if electron-cgi were to remove it (or if dotnet run would output the error to the stderr stream) , the dotnet run executable would eventually fail sometime in the future: "Non-HTTPS access will be removed in a future version"
