### ISSUE TITLE
Expressions not allowed in definition files

### ISSUE THREAD

**Issue by bosjaH** [ruidfigueiredo/electron-cgi#9]
The connection.d.ts file generates the error below during compilation.
![image](https://user-images.githubusercontent.com/23117364/77761031-a3b0b300-7037-11ea-9652-13d1363af3e9.png)

It looks like this is due to a [breaking change in typescript 2.6.1](https://stackoverflow.com/questions/47094210/d-ts-not-compiling-after-typescript-2-6-1).

**Comment by ruidfigueiredo** [comment]
@bosjaH Thanks for letting me know, I'll have a look later this evening
